const SKILLS=['woodcutting','mining','fishing','combat','constitution'];
const ITEM={};function item(id,name,type,value,opts={}){ITEM[id]={id,name,type,value,stack:opts.stack??true,heal:opts.heal||0,rare:!!opts.rare,slot:opts.slot,skill:opts.skill,tier:opts.tier,stats:opts.stats||{},cosmetic:opts.cosmetic,description:opts.description||''};}
['brushwood','pine','oak','ironwood','ancient_tree'].forEach((id,i)=>item(id,['Brushwood','Pine','Oak','Ironwood','Ancient Tree'][i],'log',[2,4,12,32,90][i]));
['stone','copper','iron','silver','starstone'].forEach((id,i)=>item(id,['Stone','Copper','Iron','Silver','Starstone'][i],'ore',[1,5,14,38,110][i]));
['minnows','riverfish','trout','swordfish','abyssal_eels'].forEach((id,i)=>item(id,['Minnows','Riverfish','Trout','Swordfish','Abyssal Eels'][i],'fish',[1,4,11,30,85][i],{heal:[1,2,4,7,10][i]}));
const toolNames={woodcutting:['Reed Hatchet','Bronzebite Axe','Crescent Axe','Embersteel Axe','Dawnroot Axe'],mining:['Pebble Pick','Bronzehook Pick','Deepdelve Pick','Moonvein Pick','Starbreaker Pick'],fishing:['Twine Net','Rivercast Rod','Barbed Rod','Stormline Rod','Abyssal Lure']};
Object.keys(toolNames).forEach(s=>toolNames[s].forEach((n,i)=>item(`${s}_tool_${i+1}`,n,'tool',0,{stack:false,slot:s,skill:s,tier:i+1})));
['cloth_vest','guard_mail','warden_plate'].forEach((id,i)=>item(id,['Cloth Vest','Guard Mail','Warden Plate'][i],'equipment', [20,500,5000][i],{stack:false,slot:'armor',stats:{defence:[1,4,10][i]}}));item('training_sword','Training Sword','equipment',10,{stack:false,slot:'weapon',stats:{accuracy:5,maxDamage:2}});item('frontier_blade','Frontier Blade','equipment',400,{stack:false,slot:'weapon',stats:{accuracy:16,maxDamage:5}});item('ancient_brand','Ancient Brand','equipment',6000,{stack:false,slot:'weapon',stats:{accuracy:34,maxDamage:10},rare:true});
['forest_sprite','ore_mite','tide_pup','rubble_imp','warden_echo'].forEach((id,i)=>item(id,['Forest Sprite','Ore Mite','Tide Pup','Rubble Imp','Warden Echo'][i],'pet',0,{stack:false,rare:true}));
const PET_INFO={forest_sprite:['Rare Woodcutting pet','Chance scales with resource XP.','Expected around level 92.'],ore_mite:['Rare Mining pet','Chance scales with resource XP.','Expected around level 92.'],tide_pup:['Rare Fishing pet','Chance scales with resource XP.','Expected around level 92.'],rubble_imp:['1 in 400 from Ruin Guards and Stone Beasts'],warden_echo:['1 in 200 from Ancient Wardens']};
const MATERIAL_DESCRIPTIONS={rat_tail:'A scavenged tail used in pack-making.',moss_fiber:'Living fiber that retains restorative energy.',ruin_shard:'A fragment of animated ruin armor.',stone_hide:'Dense plating removed from a Stone Beast.',warden_sigil:'An ancient seal carried by the wardens.',stone_heart:'A pulsing core of condensed stone.',ancient_relic:'A rare mechanism from the oldest wardens.'};
Object.entries(MATERIAL_DESCRIPTIONS).forEach(([id,description])=>item(id,id.split('_').map(w=>w[0].toUpperCase()+w.slice(1)).join(' '),'material',0,{stack:true,description}));
['amber_seed','crystal_gem','sunken_relic','golden_bough','meteor_core','pearl_hook','rat_charm','moss_crown','sentinel_eye'].forEach(id=>item(id,id.split('_').map(w=>w[0].toUpperCase()+w.slice(1)).join(' '),'rare',500,{stack:false,rare:true,description:'A rare trophy used for collection and special crafting.'}));
const RESOURCES={woodcutting:[['brushwood',1,1700,9,.006,12000],['pine',10,2400,24,.006,18000],['oak',30,3300,62,.006,30000],['ironwood',50,4500,135,.006,45000],['ancient_tree',80,6500,330,.007,80000]],mining:[['stone',1,1800,8,.12,12000],['copper',10,2600,26,.10,18000],['iron',30,3600,70,.08,32000],['silver',50,5000,150,.07,48000],['starstone',80,7200,360,.05,90000]],fishing:[['minnows',1,1600,7,.11,10000],['riverfish',10,2300,23,.09,16000],['trout',30,3300,65,.08,28000],['swordfish',50,4600,145,.07,42000],['abyssal_eels',80,7000,350,.05,85000]]};
for(const s in RESOURCES)RESOURCES[s]=RESOURCES[s].map((r,i)=>({id:r[0],name:ITEM[r[0]].name,skill:s,tier:i+1,level:r[1],interval:r[2],xp:r[3],deplete:r[4],respawn:r[5],item:r[0],rare:[{id:s==='woodcutting'?'amber_seed':s==='mining'?'crystal_gem':'sunken_relic',rate:.02},{id:s==='woodcutting'?'golden_bough':s==='mining'?'meteor_core':'pearl_hook',rate:.002}]}));
const ENEMIES=[
  {id:'cave_rat',name:'Cave Rat',hp:10,acc:45,def:2,max:2,interval:2000,xp:22,respawn:12000,drops:[{id:'coins',min:8,max:30,rate:1},{id:'bones',min:1,max:2,rate:.75},{id:'rat_tail',min:1,max:1,rate:1/3,common:true},{id:'rat_charm',min:1,max:1,rate:1/128,rare:true}]},
  {id:'moss_creature',name:'Moss Creature',hp:26,acc:58,def:5,max:4,interval:2200,xp:60,respawn:20000,drops:[{id:'coins',min:25,max:90,rate:1},{id:'bones',min:1,max:2,rate:.75},{id:'moss_fiber',min:1,max:1,rate:1/3,common:true},{id:'moss_crown',min:1,max:1,rate:1/128,rare:true}]},
  {id:'ruin_guard',name:'Ruin Guard',hp:55,acc:68,def:10,max:7,interval:2400,xp:140,respawn:35000,drops:[{id:'coins',min:60,max:180,rate:1},{id:'bones',min:1,max:2,rate:.75},{id:'ruin_shard',min:1,max:1,rate:1/2,common:true},{id:'guard_mail',min:1,max:1,rate:1/75,rare:true},{id:'sentinel_eye',min:1,max:1,rate:1/256,rare:true},{id:'rubble_imp',min:1,max:1,rate:1/400,rare:true}]},
  {id:'stone_beast',name:'Stone Beast',hp:115,acc:78,def:20,max:11,interval:2600,xp:320,respawn:55000,drops:[{id:'coins',min:130,max:450,rate:1},{id:'bones',min:1,max:2,rate:.75},{id:'stone_hide',min:1,max:1,rate:1/2,common:true},{id:'stone_heart',min:1,max:1,rate:1/40,rare:true},{id:'rubble_imp',min:1,max:1,rate:1/400,rare:true}]},
  {id:'ancient_warden',name:'Ancient Warden',hp:240,acc:88,def:34,max:18,interval:3000,xp:850,respawn:90000,drops:[{id:'coins',min:300,max:1000,rate:1},{id:'bones',min:1,max:2,rate:.75},{id:'warden_sigil',min:1,max:1,rate:1,guaranteed:true,common:true},{id:'ancient_relic',min:1,max:1,rate:1/100,rare:true},{id:'warden_echo',min:1,max:1,rate:1/200,rare:true}]}
];
item('bones','Bones','drop',3);item('coins','Coins','currency',1);
const SHOP=[...Object.keys(ITEM).filter(id=>ITEM[id].type==='tool'&&ITEM[id].tier>1).map(id=>({id,type:'item',price:ITEM[id].tier**3*180})),{id:'training_sword',type:'item',price:60},{id:'frontier_blade',type:'item',price:1200},{id:'cloth_vest',type:'item',price:80},{id:'guard_mail',type:'item',price:900},{id:'inv_4',type:'upgrade',name:'+4 inventory slots',price:700},{id:'speed_1',type:'upgrade',name:'Trail boots speed',price:900},{id:'cosmetic_cloak',type:'cosmetic',name:'Frontier Cloak',price:250},{id:'fame_100',type:'fame',name:'Buy 100 Fame',price:1000,amount:100},{id:'fame_1000',type:'fame',name:'Buy 1,000 Fame',price:15000,amount:1000}];
