const FISHING_MODES={normal:{label:'Normal',intervalMultiplier:1,sunkenRelicRate:.02,pearlHookRate:.002,description:'Standard fishing with normal speed and rare salvage rates.'},salvage:{label:'Salvage',description:'Slower fishing focused on Sunken Relics and Pearl Hooks.'}};
const RELICBOUND_TACKLE_TIERS=[null,{key:'relicbound_tackle_1',name:'Relicbound Tackle I',intervalMultiplier:1.25,sunkenRelicRate:.03,pearlHookRate:.003},{key:'relicbound_tackle_2',name:'Relicbound Tackle II',intervalMultiplier:1.15,sunkenRelicRate:.04,pearlHookRate:.004},{key:'relicbound_tackle_3',name:'Relicbound Tackle III',intervalMultiplier:1.05,sunkenRelicRate:.05,pearlHookRate:.005}];
function normalizeFishingState(){Game.state.upgrades=Game.state.upgrades||{};['relicbound_tackle_1','relicbound_tackle_2','relicbound_tackle_3'].forEach(id=>{if(Game.state.upgrades[id]!==true)Game.state.upgrades[id]=false});if(Game.state.upgrades.relicbound_tackle_3){Game.state.upgrades.relicbound_tackle_2=true;Game.state.upgrades.relicbound_tackle_1=true}else if(Game.state.upgrades.relicbound_tackle_2)Game.state.upgrades.relicbound_tackle_1=true;if(!Game.state.fishing)Game.state.fishing={mode:'normal'};if(!['normal','salvage'].includes(Game.state.fishing.mode))Game.state.fishing.mode='normal';if(Game.state.fishing.mode==='salvage'&&!Game.state.upgrades.relicbound_tackle_1)Game.state.fishing.mode='normal'}
function relicboundTackleTier(){normalizeFishingState();if(Game.state.upgrades.relicbound_tackle_3)return 3;if(Game.state.upgrades.relicbound_tackle_2)return 2;if(Game.state.upgrades.relicbound_tackle_1)return 1;return 0}
function fishingModeSettings(){normalizeFishingState();const tier=relicboundTackleTier();if(Game.state.fishing.mode==='salvage'&&tier>0)return {...FISHING_MODES.salvage,...RELICBOUND_TACKLE_TIERS[tier],mode:'salvage',tier};return {...FISHING_MODES.normal,mode:'normal',tier}}
function fishingIntervalMultiplier(resource){return resource&&resource.skill==='fishing'?fishingModeSettings().intervalMultiplier:1}
function fishingRareTable(resource){if(!resource||resource.skill!=='fishing')return resource?resource.rare:[];const s=fishingModeSettings();return [{id:'sunken_relic',rate:s.sunkenRelicRate},{id:'pearl_hook',rate:s.pearlHookRate}]}
function setFishingMode(mode){normalizeFishingState();if(!['normal','salvage'].includes(mode))return false;if(mode==='salvage'&&!Game.state.upgrades.relicbound_tackle_1){logMsg('Relicbound Tackle I is required to use Salvage Fishing.','bad');return false}if(Game.state.fishing.mode===mode)return true;Game.state.fishing.mode=mode;if(Game.state.action.type==='gathering'){const o=Game.objects.find(x=>x.id===Game.state.action.target);if(o&&resDef(o.defId).skill==='fishing')setAction({type:'idle'})}logMsg(`Fishing mode changed to ${FISHING_MODES[mode].label}.`,'rare');Game.uiDirty=true;return true}
function openFishingMode(){normalizeFishingState();if(!Game.state.upgrades.relicbound_tackle_1){modal('Fishing Mode',`<div class="mode locked-mode">Relicbound Tackle I is required to unlock Salvage Fishing.</div><button onclick="setFishingMode('normal');openFishingMode()">Keep Normal Fishing</button>`);return}const s=fishingModeSettings(),tier=relicboundTackleTier(),pen=Math.round((s.intervalMultiplier-1)*100);modal('Fishing Mode',`<div class="mode current-mode">Current mode: <b>${s.label}</b></div><div>Normal Fishing: existing speed, XP, fish, pet, depletion, and rare rates.</div><div>Salvage Fishing: slower catches with improved Sunken Relic and Pearl Hook rates.</div><div>Current tackle tier: ${tier?RELICBOUND_TACKLE_TIERS[tier].name:'None'}</div><div>Current speed penalty: ${pen}% slower</div><div>Current Sunken Relic rate: ${(s.sunkenRelicRate*100).toFixed(1).replace('.0','')}%</div><div>Current Pearl Hook rate: ${(s.pearlHookRate*100).toFixed(1)}%</div><button onclick="setFishingMode('normal');openFishingMode()">Select Normal</button> <button onclick="setFishingMode('salvage');openFishingMode()">Select Salvage</button>`)}
function fishingModeButtonLabel(){normalizeFishingState();return `Fishing: ${FISHING_MODES[Game.state.fishing.mode].label}`}
