const FORGE_RECIPES=[
{id:'pack_rat_satchel',name:'Pack Rat Satchel',description:'Permanent +4 inventory slots. Stacks with the Merchant Hall inventory upgrade.',materials:{rat_tail:20,rat_charm:1},coins:500,result:{type:'upgrade',id:'pack_rat_satchel'},repeatable:false},
{id:'mossbound_charm',name:'Mossbound Charm',description:'Double passive out-of-combat health regeneration: 1 HP every 1.5 seconds instead of 3 seconds.',materials:{moss_fiber:20,moss_crown:1},coins:1000,result:{type:'upgrade',id:'mossbound_charm'},repeatable:false},
{id:'sentinel_lens',name:'Sentinel Lens',description:'Permanent +8 player combat accuracy.',materials:{ruin_shard:20,sentinel_eye:1},coins:1500,result:{type:'upgrade',id:'sentinel_lens'},repeatable:false},
{id:'warden_plate',name:'Warden Plate',description:'Forge dense Stone Beast plating into a Warden Plate armor piece.',materials:{stone_hide:30,stone_heart:3},coins:2500,result:{type:'item',id:'warden_plate',qty:1},repeatable:true},
{id:'ancient_brand',name:'Ancient Brand',description:'Rebuild an Ancient Brand weapon from warden seals and an Ancient Relic.',materials:{warden_sigil:10,ancient_relic:1},coins:5000,result:{type:'item',id:'ancient_brand',qty:1},repeatable:true},
{id:'heartwood_totem_1',name:'Heartwood Totem I',description:'Permanent totem upgrade that unlocks Grovekeeping mode.',materials:{amber_seed:20,golden_bough:1},coins:2500,result:{type:'upgrade',id:'heartwood_totem_1'},repeatable:false,upgradeFamily:'heartwood_totem',upgradeTier:1},
{id:'heartwood_totem_2',name:'Heartwood Totem II',description:'Permanent totem upgrade that improves Grovekeeping.',materials:{amber_seed:50,golden_bough:2},coins:7500,requiresUpgrade:'heartwood_totem_1',requiresName:'Heartwood Totem I',result:{type:'upgrade',id:'heartwood_totem_2'},repeatable:false,upgradeFamily:'heartwood_totem',upgradeTier:2},
{id:'heartwood_totem_3',name:'Heartwood Totem III',description:'Permanent totem upgrade with the final Grovekeeping improvement.',materials:{amber_seed:100,golden_bough:3},coins:20000,requiresUpgrade:'heartwood_totem_2',requiresName:'Heartwood Totem II',result:{type:'upgrade',id:'heartwood_totem_3'},repeatable:false,upgradeFamily:'heartwood_totem',upgradeTier:3},
{id:'deepcore_resonator_1',name:'Deepcore Resonator I',description:'Permanent resonator upgrade that unlocks Prospecting mode.',materials:{crystal_gem:20,meteor_core:1},coins:2500,result:{type:'upgrade',id:'deepcore_resonator_1'},repeatable:false,upgradeFamily:'deepcore_resonator',upgradeTier:1},
{id:'deepcore_resonator_2',name:'Deepcore Resonator II',description:'Permanent resonator upgrade that improves Prospecting.',materials:{crystal_gem:50,meteor_core:2},coins:7500,requiresUpgrade:'deepcore_resonator_1',requiresName:'Deepcore Resonator I',result:{type:'upgrade',id:'deepcore_resonator_2'},repeatable:false,upgradeFamily:'deepcore_resonator',upgradeTier:2},
{id:'deepcore_resonator_3',name:'Deepcore Resonator III',description:'Permanent resonator upgrade with the final Prospecting improvement.',materials:{crystal_gem:100,meteor_core:3},coins:20000,requiresUpgrade:'deepcore_resonator_2',requiresName:'Deepcore Resonator II',result:{type:'upgrade',id:'deepcore_resonator_3'},repeatable:false,upgradeFamily:'deepcore_resonator',upgradeTier:3},
{id:'relicbound_tackle_1',name:'Relicbound Tackle I',description:'Permanent tackle upgrade that unlocks Salvage Fishing mode.',materials:{sunken_relic:20,pearl_hook:1},coins:2500,result:{type:'upgrade',id:'relicbound_tackle_1'},repeatable:false,upgradeFamily:'relicbound_tackle',upgradeTier:1},
{id:'relicbound_tackle_2',name:'Relicbound Tackle II',description:'Permanent tackle upgrade that improves Salvage Fishing efficiency.',materials:{sunken_relic:50,pearl_hook:2},coins:7500,requiresUpgrade:'relicbound_tackle_1',requiresName:'Relicbound Tackle I',result:{type:'upgrade',id:'relicbound_tackle_2'},repeatable:false,upgradeFamily:'relicbound_tackle',upgradeTier:2},
{id:'relicbound_tackle_3',name:'Relicbound Tackle III',description:'Permanent tackle upgrade with the final Salvage Fishing improvement.',materials:{sunken_relic:100,pearl_hook:3},coins:20000,requiresUpgrade:'relicbound_tackle_2',requiresName:'Relicbound Tackle II',result:{type:'upgrade',id:'relicbound_tackle_3'},repeatable:false,upgradeFamily:'relicbound_tackle',upgradeTier:3},
];
function formatDropRate(rate){if(rate>=1)return '100% (guaranteed)';const denom=Math.round(1/rate);return `${(rate*100).toFixed(rate<.01?2:rate<.1?1:0)}% (1 in ${denom.toLocaleString()})`}
function ownedQuantity(id){return typeof ownedItemQuantity==='function'?ownedItemQuantity(id):Game.state.inventory.filter(s=>s.id===id).reduce((n,s)=>n+s.qty,0)+(Game.state.bank[id]||0)}
function materialShortfallText(id,need){const def=itemDef(id),owned=ownedQuantity(id),miss=need-owned;if(miss<=0)return '';return miss===1&&!def.stack?`Need a ${def.name}`:`Need ${miss.toLocaleString()} more ${def.name}${miss===1?'':'s'}`}
function forgeRecipe(id){return FORGE_RECIPES.find(r=>r.id===id)}
function normalizeForgeUpgrades(){Game.state.upgrades=Game.state.upgrades||{};['pack_rat_satchel','mossbound_charm','sentinel_lens','heartwood_totem_1','heartwood_totem_2','heartwood_totem_3','deepcore_resonator_1','deepcore_resonator_2','deepcore_resonator_3','relicbound_tackle_1','relicbound_tackle_2','relicbound_tackle_3'].forEach(id=>{if(Game.state.upgrades[id]!==true)Game.state.upgrades[id]=false});if(!Game.state.regen)Game.state.regen={last:performance.now?performance.now():0}}
function forgeResultName(recipe){return recipe.result.type==='upgrade'?recipe.name:itemDef(recipe.result.id).name}
function canCraftRecipe(recipe){normalizeForgeUpgrades();if(!recipe)return{ok:false,reason:'Recipe unavailable'};if(!recipe.repeatable&&Game.state.upgrades[recipe.result.id])return{ok:false,reason:'Already forged'};if(recipe.requiresUpgrade&&!Game.state.upgrades[recipe.requiresUpgrade])return{ok:false,reason:`Requires ${recipe.requiresName||recipe.requiresUpgrade}`};for(const [id,need] of Object.entries(recipe.materials)){const reason=materialShortfallText(id,need);if(reason)return{ok:false,reason}}if(Game.state.coins<recipe.coins)return{ok:false,reason:`Need ${(recipe.coins-Game.state.coins).toLocaleString()} more coins`};if(recipe.result.type==='item'&&!hasSpaceFor(recipe.result.id))return{ok:false,reason:'Inventory full'};return{ok:true,reason:''}}
function removeOwnedItems(id,qty){return removeOwnedItemQuantity(id,qty)}
function craftRecipe(recipeId){const recipe=forgeRecipe(recipeId);const validation=canCraftRecipe(recipe);if(!validation.ok)return forgeFeedback(validation.reason,'bad');for(const [id,need] of Object.entries(recipe.materials))if(ownedQuantity(id)<need)return forgeFeedback(materialShortfallText(id,need),'bad');if(Game.state.coins<recipe.coins)return forgeFeedback(`Need ${(recipe.coins-Game.state.coins).toLocaleString()} more coins`,'bad');if(recipe.result.type==='item'&&!hasSpaceFor(recipe.result.id))return forgeFeedback('Inventory full','bad');for(const [id,need] of Object.entries(recipe.materials))removeOwnedItems(id,need);Game.state.coins-=recipe.coins;if(recipe.result.type==='upgrade'){if(Game.state.upgrades[recipe.result.id])return forgeFeedback('Already forged','bad');Game.state.upgrades[recipe.result.id]=true;if(typeof normalizeGatheringModes==='function')normalizeGatheringModes();if(recipe.result.id==='pack_rat_satchel')Game.state.invCap+=4}else addItem(recipe.result.id,recipe.result.qty||1);const msg=`Forged ${forgeResultName(recipe)}.`;forgeFeedback(msg,'rare')}
function forgeFeedback(text,cls){Game.forgeMessage={text,cls};logMsg(text,cls);Game.uiDirty=true;openForge(Game.forgeMessage)}
function recipeHtml(recipe){const v=canCraftRecipe(recipe);const req=Object.entries(recipe.materials).map(([id,need])=>`<div class="forge-req ${ownedQuantity(id)>=need?'good':'bad'}">${itemDef(id).name}: ${ownedQuantity(id).toLocaleString()}/${need.toLocaleString()}</div>`).join('');return `<div class="entry forge-recipe ${v.ok?'craftable':'blocked'}"><h3>${recipe.name}</h3><p>${recipe.description}</p><div><b>Result:</b> ${forgeResultName(recipe)}</div><div><b>Coins:</b> ${Game.state.coins.toLocaleString()}/${recipe.coins.toLocaleString()}</div><div><b>Repeatable:</b> ${recipe.repeatable?'Yes':'No'}</div>${req}<button onclick="craftRecipe('${recipe.id}')" ${v.ok?'':'disabled'}>Craft</button><span class="forge-status ${v.ok?'good':'bad'}">${v.ok?'Ready':v.reason}</span></div>`}
function openForge(message){normalizeForgeUpgrades();const feedback=(message||Game.forgeMessage)?`<div class="msg ${(message||Game.forgeMessage).cls||''}">${(message||Game.forgeMessage).text}</div>`:'<div class="msg"></div>';modal('Frontier Forge',`<div class="forge-summary"><b>Coins:</b> ${Game.state.coins.toLocaleString()}</div>${feedback}${FORGE_RECIPES.map(recipeHtml).join('')}`)}
function getRegenInterval(){return Game.state.upgrades&&Game.state.upgrades.mossbound_charm?1500:3000}
function sentinelAccuracyBonus(){return Game.state.upgrades&&Game.state.upgrades.sentinel_lens?8:0}
