const GATHERING_MODE_CONFIG={woodcutting:{label:'Woodcutting',normalMode:'normal',normalLabel:'Normal',alternateMode:'grovekeeping',alternateLabel:'Grovekeeping',upgradeFamily:'heartwood_totem',upgradeName:'Heartwood Totem',commonRare:'amber_seed',catalystRare:'golden_bough',secondary:'depletion'},mining:{label:'Mining',normalMode:'normal',normalLabel:'Normal',alternateMode:'prospecting',alternateLabel:'Prospecting',upgradeFamily:'deepcore_resonator',upgradeName:'Deepcore Resonator',commonRare:'crystal_gem',catalystRare:'meteor_core',secondary:'bonusOre'},fishing:{label:'Fishing',normalMode:'normal',normalLabel:'Normal',alternateMode:'salvage',alternateLabel:'Salvage',upgradeFamily:'relicbound_tackle',upgradeName:'Relicbound Tackle',commonRare:'sunken_relic',catalystRare:'pearl_hook',secondary:'none'}};
const GATHERING_MODE_TIERS=[{tier:0,intervalMultiplier:1,commonRareRate:.02,catalystRareRate:.002,depletionMultiplier:1,bonusQuantityChance:0},{tier:1,intervalMultiplier:1.25,commonRareRate:.03,catalystRareRate:.003,depletionMultiplier:.8,bonusQuantityChance:.05},{tier:2,intervalMultiplier:1.15,commonRareRate:.04,catalystRareRate:.004,depletionMultiplier:.65,bonusQuantityChance:.1},{tier:3,intervalMultiplier:1.05,commonRareRate:.05,catalystRareRate:.005,depletionMultiplier:.5,bonusQuantityChance:.15}];
function gatheringFamilyRecipeIds(family){return [1,2,3].map(t=>`${family}_${t}`)}
function normalizeGatheringUpgrades(){Game.state.upgrades=Game.state.upgrades||{};Object.values(GATHERING_MODE_CONFIG).forEach(c=>gatheringFamilyRecipeIds(c.upgradeFamily).forEach(id=>{if(Game.state.upgrades[id]!==true)Game.state.upgrades[id]=false}));Object.values(GATHERING_MODE_CONFIG).forEach(c=>{const u=Game.state.upgrades;if(u[`${c.upgradeFamily}_3`]){u[`${c.upgradeFamily}_2`]=true;u[`${c.upgradeFamily}_1`]=true}else if(u[`${c.upgradeFamily}_2`])u[`${c.upgradeFamily}_1`]=true})}
function normalizeGatheringModes(){normalizeGatheringUpgrades();const legacy=Game.state.fishing&&Game.state.fishing.mode;if(!Game.state.gatheringModes)Game.state.gatheringModes={woodcutting:'normal',mining:'normal',fishing:legacy||'normal'};Object.entries(GATHERING_MODE_CONFIG).forEach(([skill,c])=>{let mode=Game.state.gatheringModes[skill];if(skill==='fishing'&&legacy&&(!mode||mode==='normal'))mode=legacy;if(![c.normalMode,c.alternateMode].includes(mode))mode=c.normalMode;if(mode===c.alternateMode&&!Game.state.upgrades[`${c.upgradeFamily}_1`])mode=c.normalMode;Game.state.gatheringModes[skill]=mode});Game.state.fishing=Game.state.fishing||{};Game.state.fishing.mode=Game.state.gatheringModes.fishing}
function normalizeFishingState(){normalizeGatheringModes()}
function gatheringUpgradeTier(skillOrFamily){normalizeGatheringUpgrades();let family=GATHERING_MODE_CONFIG[skillOrFamily]?GATHERING_MODE_CONFIG[skillOrFamily].upgradeFamily:skillOrFamily;if(Game.state.upgrades[`${family}_3`])return 3;if(Game.state.upgrades[`${family}_2`])return 2;if(Game.state.upgrades[`${family}_1`])return 1;return 0}
function relicboundTackleTier(){return gatheringUpgradeTier('fishing')}
function gatheringModeSettings(skill){normalizeGatheringModes();const c=GATHERING_MODE_CONFIG[skill],tier=gatheringUpgradeTier(skill),mode=Game.state.gatheringModes[skill],base=GATHERING_MODE_TIERS[mode===c.alternateMode?tier:0];return {...base,mode,tier,label:mode===c.alternateMode?c.alternateLabel:c.normalLabel,commonRare:c.commonRare,catalystRare:c.catalystRare,config:c}}
function fishingModeSettings(){return gatheringModeSettings('fishing')}
function gatheringIntervalMultiplier(resource){return resource?gatheringModeSettings(resource.skill).intervalMultiplier:1}
function fishingIntervalMultiplier(resource){return resource&&resource.skill==='fishing'?gatheringIntervalMultiplier(resource):1}
function gatheringRareTable(resource){if(!resource)return[];const s=gatheringModeSettings(resource.skill);return[{id:s.commonRare,rate:s.commonRareRate},{id:s.catalystRare,rate:s.catalystRareRate}]}
function fishingRareTable(resource){return resource&&resource.skill==='fishing'?gatheringRareTable(resource):resource?resource.rare:[]}
function gatheringDepletionChance(resource){if(!resource)return 0;const s=gatheringModeSettings(resource.skill);return resource.deplete*(resource.skill==='woodcutting'?s.depletionMultiplier:1)}
function gatheringBonusQuantity(resource){if(!resource||resource.skill!=='mining')return 0;const s=gatheringModeSettings('mining');return s.mode==='prospecting'&&Math.random()<s.bonusQuantityChance?1:0}
function setGatheringMode(skill,mode){normalizeGatheringModes();const c=GATHERING_MODE_CONFIG[skill];if(!c||![c.normalMode,c.alternateMode].includes(mode))return false;if(mode===c.alternateMode&&!Game.state.upgrades[`${c.upgradeFamily}_1`]){logMsg(`${c.upgradeName} I is required to use ${c.alternateLabel}.`,'bad');return false}if(Game.state.gatheringModes[skill]===mode)return true;Game.state.gatheringModes[skill]=mode;if(skill==='fishing')Game.state.fishing.mode=mode;if(Game.state.action.type==='gathering'){const o=Game.objects.find(x=>x.id===Game.state.action.target);if(o&&resDef(o.defId).skill===skill)setAction({type:'idle'})}logMsg(`${c.label} mode changed to ${mode===c.alternateMode?c.alternateLabel:c.normalLabel}.`,'rare');Game.uiDirty=true;return true}
function setFishingMode(mode){return setGatheringMode('fishing',mode)}
function nextGatheringUpgradeRecipe(family){normalizeGatheringUpgrades();if(typeof forgeRecipe!=='function')return null;for(const id of gatheringFamilyRecipeIds(family))if(!Game.state.upgrades[id])return forgeRecipe(id);return null}
function nextRelicboundRecipe(){return nextGatheringUpgradeRecipe('relicbound_tackle')}
function pct(n){return (n*100).toFixed(n<.01?1:0).replace('.0','')+'%'}
function openGatheringModes(){normalizeGatheringModes();modal('Gathering Modes',Object.entries(GATHERING_MODE_CONFIG).map(([skill,c])=>{const s=gatheringModeSettings(skill),locked=!Game.state.upgrades[`${c.upgradeFamily}_1`],pen=Math.round((s.intervalMultiplier-1)*100),extra=skill==='woodcutting'?`<div>Current depletion reduction: ${Math.round((1-s.depletionMultiplier)*100)}%</div>`:skill==='mining'?`<div>Current bonus-ore chance: ${pct(s.bonusQuantityChance)}</div>`:'';return `<section class="gathering-mode-section ${locked?'locked-mode':''}"><h3>${c.label}</h3><div class="tier-label">Current ${c.upgradeName} tier: ${s.tier}</div><div class="current-mode">Current mode: <b>${s.label}</b></div><div>Normal: existing speed, XP, quantity, pet, depletion, and rare rates.</div><div>${c.alternateLabel}: slower gathering with improved ${itemDef(c.commonRare).name} and ${itemDef(c.catalystRare).name} rates${skill==='woodcutting'?' and reduced tree depletion':skill==='mining'?' plus a chance for one extra ore':''}.</div><div>Current speed penalty: ${pen}% slower</div><div>Current ${itemDef(c.commonRare).name} rate: ${pct(s.commonRareRate)}</div><div>Current ${itemDef(c.catalystRare).name} rate: ${pct(s.catalystRareRate)}</div>${extra}${locked?`<div class="reservation-warning">Locked: ${c.upgradeName} I is required.</div>`:''}<button onclick="setGatheringMode('${skill}','normal');openGatheringModes()">Select Normal</button> <button onclick="setGatheringMode('${skill}','${c.alternateMode}');openGatheringModes()" ${locked?'disabled':''}>Select ${c.alternateLabel}</button></section>`}).join(''))}
function openFishingMode(){openGatheringModes()}
function fishingModeButtonLabel(){return 'Gathering Modes'}
