function enemyDropPityKey(enemyId, dropId) { return `${enemyId}:${dropId}`; }
function enemyDropPityEligible(drop) { return !!(drop && drop.pity === true); }
function enemyDropPityDenominator(drop) { return Math.round(1 / drop.rate); }
function enemyDropPityGuaranteeAttempt(drop) { return enemyDropPityDenominator(drop) * 3; }
function enemyDropPityEntries() { const entries = {}; for (const enemy of ENEMIES) for (const drop of enemy.drops) if (enemyDropPityEligible(drop)) entries[enemyDropPityKey(enemy.id, drop.id)] = { enemy, drop }; return entries; }
function normalizeEnemyDropPityValue(value, max) { const number = typeof value === 'string' && value.trim() !== '' ? Number(value) : value; if (!Number.isFinite(number) || number < 0) return 0; return Math.min(Math.floor(number), max); }
function ensureEnemyDropPityState() { Game.state.pity = Game.state.pity && typeof Game.state.pity === 'object' ? Game.state.pity : {}; Game.state.pity.enemyDrops = Game.state.pity.enemyDrops && typeof Game.state.pity.enemyDrops === 'object' ? Game.state.pity.enemyDrops : {}; Game.state.migrations = Game.state.migrations && typeof Game.state.migrations === 'object' ? Game.state.migrations : {}; Game.state.kills = Game.state.kills && typeof Game.state.kills === 'object' ? Game.state.kills : {}; Game.state.collection = Game.state.collection && typeof Game.state.collection === 'object' ? Game.state.collection : {}; }
function normalizeEnemyDropPity(options = {}) { ensureEnemyDropPityState(); const entries = enemyDropPityEntries(); const next = {}; for (const [key, entry] of Object.entries(entries)) { const guarantee = enemyDropPityGuaranteeAttempt(entry.drop); if (options.migrateLegacy) { const discovered = (Game.state.collection[entry.drop.id] || 0) > 0; const kills = normalizeEnemyDropPityValue(Game.state.kills[entry.enemy.id] || 0, guarantee - 1); next[key] = discovered ? 0 : kills; } else { next[key] = normalizeEnemyDropPityValue(Game.state.pity.enemyDrops[key], guarantee); } } Game.state.pity.enemyDrops = next; Game.state.migrations.enemyDropPityV1 = true; }
function enemyDropPityStreak(enemyId, dropId) { ensureEnemyDropPityState(); return normalizeEnemyDropPityValue(Game.state.pity.enemyDrops[enemyDropPityKey(enemyId, dropId)], Number.MAX_SAFE_INTEGER); }
function enemyDropPityNextAttempt(enemyId, drop) { return enemyDropPityStreak(enemyId, drop.id) + 1; }
function enemyDropPityRate(baseRate, attempt) { const denominator = Math.round(1 / baseRate); let rate; if (attempt <= denominator) rate = baseRate; else if (attempt >= denominator * 3) rate = 1; else { const progress = (attempt - denominator) / (denominator * 2); rate = baseRate + (1 - baseRate) * Math.pow(progress, 4); } return Math.max(baseRate, Math.min(1, rate)); }
function enemyDropCurrentRate(enemyId, drop) { return enemyDropPityEligible(drop) ? enemyDropPityRate(drop.rate, enemyDropPityNextAttempt(enemyId, drop)) : drop.rate; }
function enemyDropKillsUntilGuarantee(enemyId, drop) { return Math.max(0, enemyDropPityGuaranteeAttempt(drop) - enemyDropPityStreak(enemyId, drop.id)); }
function rollEnemyDrop(enemyId, drop) { if (!enemyDropPityEligible(drop)) return { eligible: false, enemyId, dropId: drop.id, dropped: Math.random() < drop.rate, effectiveRate: drop.rate }; ensureEnemyDropPityState(); const key = enemyDropPityKey(enemyId, drop.id), attempt = enemyDropPityNextAttempt(enemyId, drop), effectiveRate = enemyDropPityRate(drop.rate, attempt), dropped = Math.random() < effectiveRate; Game.state.pity.enemyDrops[key] = Math.min(attempt, enemyDropPityGuaranteeAttempt(drop)); return { eligible: true, key, enemyId, dropId: drop.id, attempt, baseRate: drop.rate, effectiveRate, dropped }; }
function settleEnemyDropRoll(result, delivered) { if (result && result.eligible && delivered) Game.state.pity.enemyDrops[result.key] = 0; }
function formatEnemyDropPityPercent(rate) { if (rate >= 1) return '100%'; return `${(rate * 100).toFixed(rate < .1 ? 2 : 1).replace(/\.0+$/, '').replace(/(\.\d*[1-9])0+$/, '$1')}%`; }
