const GATHERING_SKILLS=['woodcutting','mining','fishing'];
const GATHERING_UPGRADE_FAMILIES=['heartwood_totem','deepcore_resonator','relicbound_tackle'];
const TASKS=[
{id:'gather_25',name:'Gather 25 total resources',description:'Gather resources through Woodcutting, Mining, or Fishing.',target:25,condition:{type:'counter',key:'gathered'},reward:{coins:100},levelXpTarget:{type:'lowestGathering'},stage:'introduction',order:10},
{id:'coins_500',name:'Earn 500 coins',description:'Earn coins from gathering, combat, sales, or task rewards.',target:500,condition:{type:'counter',key:'coinsEarned'},reward:{fame:10},levelXpTarget:{type:'lowestAny'},stage:'introduction',order:20},
{id:'mine_iron',name:'Reach Mining level 30',description:'Train Mining until you can work iron deposits.',target:30,condition:{type:'skillLevel',skill:'mining'},reward:{coins:700},levelXpTarget:{type:'skill',skill:'mining'},stage:'introduction',order:30},
{id:'rat_10',name:'Defeat 10 Cave Rats',description:'Clear Cave Rats from the frontier.',target:10,condition:{type:'enemyKills',enemy:'cave_rat'},reward:{xp:{combat:100}},levelXpTarget:{type:'skill',skill:'combat'},stage:'introduction',order:40},
{id:'tool_t3',name:'Own any tier 3 tool',description:'Own at least one tier-three gathering tool.',target:1,condition:{type:'anyToolTier',tier:3},reward:{coins:500},levelXpTarget:{type:'lowestGathering'},stage:'introduction',order:50},
{id:'regions',name:'Discover every major region',description:'Discover all five major regions of the frontier.',target:5,condition:{type:'regions'},reward:{inv:4},levelXpTarget:{type:'lowestAny'},stage:'introduction',order:60},
{id:'fame_100',name:'Purchase 100 Fame',description:'Buy Fame from the Merchant Hall.',target:100,condition:{type:'fameBought'},reward:{coins:250},levelXpTarget:{type:'lowestAny'},stage:'introduction',order:70},
{id:'pet',name:'Find any pet',description:'Own at least one pet.',target:1,condition:{type:'petCount'},reward:{fame:50},levelXpTarget:{type:'lowestAny'},stage:'introduction',order:80},
{id:'tasks_5',name:'Claim 5 other tasks',description:'Claim five other task rewards.',target:5,condition:{type:'tasksClaimed'},reward:{fame:100},levelXpTarget:{type:'lowestAny'},stage:'introduction',order:90},
{id:'balanced_10',name:'Reach level 10 in Woodcutting, Mining, and Fishing',description:'Build a balanced foundation in the three gathering skills.',target:10,condition:{type:'allSkillLevels',skills:GATHERING_SKILLS},reward:{coins:500},levelXpTarget:{type:'lowestGathering'},stage:'early',order:100},
{id:'toolbelt_t2',name:'Own a tier 2 tool for all three gathering skills',description:'Upgrade each gathering skill to at least a tier 2 tool.',target:3,condition:{type:'allGatheringToolTier',skills:GATHERING_SKILLS,tier:2},reward:{coins:600},levelXpTarget:{type:'lowestGathering'},requires:['balanced_10'],stage:'early',order:110},
{id:'forge_any',name:'Complete your first Frontier Forge recipe',description:'Complete any recipe at the Frontier Forge.',target:1,condition:{type:'forgedAny'},reward:{coins:400},levelXpTarget:{type:'lowestAny'},stage:'early',order:120},
{id:'moss_10',name:'Defeat 10 Moss Creatures',description:'Push deeper into living forest threats.',target:10,condition:{type:'enemyKills',enemy:'moss_creature'},reward:{coins:400},levelXpTarget:{type:'skill',skill:'combat'},requires:['rat_10'],stage:'early',order:130},
{id:'pack_satchel',name:'Forge the Pack Rat Satchel',description:'Forge the Pack Rat Satchel at the Frontier Forge.',target:1,condition:{type:'upgradeOwned',upgrade:'pack_rat_satchel'},reward:{coins:500,fame:25},levelXpTarget:{type:'lowestAny'},requires:['rat_10'],stage:'early',order:140},
{id:'mossbound_charm',name:'Forge the Mossbound Charm',description:'Forge the Mossbound Charm at the Frontier Forge.',target:1,condition:{type:'upgradeOwned',upgrade:'mossbound_charm'},reward:{coins:750,fame:25},levelXpTarget:{type:'skill',skill:'constitution'},requires:['moss_10'],stage:'early',order:150},
{id:'heartwood_1',name:'Forge Heartwood Totem I',description:'Unlock Grovekeeping by forging Heartwood Totem I.',target:1,condition:{type:'upgradeOwned',upgrade:'heartwood_totem_1'},reward:{coins:500,fame:25},levelXpTarget:{type:'skill',skill:'woodcutting'},stage:'early',order:160},
{id:'deepcore_1',name:'Forge Deepcore Resonator I',description:'Unlock Prospecting by forging Deepcore Resonator I.',target:1,condition:{type:'upgradeOwned',upgrade:'deepcore_resonator_1'},reward:{coins:500,fame:25},levelXpTarget:{type:'skill',skill:'mining'},stage:'early',order:170},
{id:'relicbound_1',name:'Forge Relicbound Tackle I',description:'Unlock Salvage Fishing by forging Relicbound Tackle I.',target:1,condition:{type:'upgradeOwned',upgrade:'relicbound_tackle_1'},reward:{coins:500,fame:25},levelXpTarget:{type:'skill',skill:'fishing'},stage:'early',order:180},
{id:'grovekeeping_100',name:'Complete 100 successful Grovekeeping actions',description:'Gather successfully while Woodcutting in Grovekeeping mode.',target:100,condition:{type:'modeActions',skill:'woodcutting',mode:'grovekeeping'},reward:{coins:350,fame:15},levelXpTarget:{type:'skill',skill:'woodcutting'},requires:['heartwood_1'],stage:'modes',order:190},
{id:'prospecting_100',name:'Complete 100 successful Prospecting actions',description:'Gather successfully while Mining in Prospecting mode.',target:100,condition:{type:'modeActions',skill:'mining',mode:'prospecting'},reward:{coins:350,fame:15},levelXpTarget:{type:'skill',skill:'mining'},requires:['deepcore_1'],stage:'modes',order:200},
{id:'salvage_100',name:'Complete 100 successful Salvage Fishing actions',description:'Gather successfully while Fishing in Salvage mode.',target:100,condition:{type:'modeActions',skill:'fishing',mode:'salvage'},reward:{coins:350,fame:15},levelXpTarget:{type:'skill',skill:'fishing'},requires:['relicbound_1'],stage:'modes',order:210},
{id:'rare_goods_10',name:'Sell 10 Rare Goods',description:'Sell gathering Rare Goods at the Merchant Hall.',target:10,condition:{type:'rareGoodsSold'},reward:{coins:500,fame:25},levelXpTarget:{type:'lowestGathering'},requiresAny:['heartwood_1','deepcore_1','relicbound_1'],stage:'modes',order:220},
{id:'gathering_tier1_all',name:'Forge all three tier I gathering upgrades',description:'Forge Heartwood Totem I, Deepcore Resonator I, and Relicbound Tackle I.',target:3,condition:{type:'allUpgradeFamiliesTier',families:GATHERING_UPGRADE_FAMILIES,tier:1},reward:{coins:2000,fame:100},levelXpTarget:{type:'lowestGathering'},requires:['heartwood_1','deepcore_1','relicbound_1'],stage:'modes',order:230},
{id:'gathering_30',name:'Reach level 30 in Woodcutting, Mining, and Fishing',description:'Advance all gathering skills into midgame.',target:30,condition:{type:'allSkillLevels',skills:GATHERING_SKILLS},reward:{coins:2000},levelXpTarget:{type:'lowestGathering'},requires:['balanced_10'],stage:'midgame',order:240},
{id:'toolbelt_t3_all',name:'Own a tier 3 tool for all three gathering skills',description:'Own tier 3 tools for Woodcutting, Mining, and Fishing.',target:3,condition:{type:'allGatheringToolTier',skills:GATHERING_SKILLS,tier:3},reward:{coins:1500},levelXpTarget:{type:'lowestGathering'},requires:['toolbelt_t2'],stage:'midgame',order:250},
{id:'ruin_guard_25',name:'Defeat 25 Ruin Guards',description:'Campaign through the Northern Ruins.',target:25,condition:{type:'enemyKills',enemy:'ruin_guard'},reward:{coins:1500,fame:50},levelXpTarget:{type:'skill',skill:'combat'},requires:['moss_10'],stage:'midgame',order:260},
{id:'sentinel_lens',name:"Forge the Sentinel's Lens",description:'Forge the Sentinel Lens at the Frontier Forge.',target:1,condition:{type:'upgradeOwned',upgrade:'sentinel_lens'},reward:{coins:1000,fame:50},levelXpTarget:{type:'skill',skill:'combat'},requires:['ruin_guard_25'],stage:'midgame',order:270},
{id:'gathering_tier2_any',name:'Forge any tier II gathering upgrade',description:'Refine any gathering-upgrade family to tier II.',target:1,condition:{type:'anyUpgradeTier',families:GATHERING_UPGRADE_FAMILIES,tier:2},reward:{coins:2500,fame:100},levelXpTarget:{type:'lowestGathering'},requiresAny:['heartwood_1','deepcore_1','relicbound_1'],stage:'midgame',order:280},
{id:'tasks_15',name:'Claim 15 other tasks',description:'Claim fifteen other task rewards.',target:15,condition:{type:'tasksClaimed'},reward:{fame:250},levelXpTarget:{type:'lowestAny'},requires:['tasks_5'],stage:'midgame',order:290},
{id:'gathering_tier2_all',name:'Forge all three tier II gathering upgrades',description:'Refine all gathering-upgrade families to tier II.',target:3,condition:{type:'allUpgradeFamiliesTier',families:GATHERING_UPGRADE_FAMILIES,tier:2},reward:{coins:7500,fame:250},levelXpTarget:{type:'lowestGathering'},requires:['gathering_tier1_all'],stage:'later',order:300},
{id:'gathering_50',name:'Reach level 50 in Woodcutting, Mining, and Fishing',description:'Master reliable gathering across all three skills.',target:50,condition:{type:'allSkillLevels',skills:GATHERING_SKILLS},reward:{coins:5000},levelXpTarget:{type:'lowestGathering'},requires:['gathering_30'],stage:'later',order:310},
{id:'stone_beast_20',name:'Defeat 20 Stone Beasts',description:'Break the Stone Beasts roaming the frontier.',target:20,condition:{type:'enemyKills',enemy:'stone_beast'},reward:{coins:5000,fame:100},levelXpTarget:{type:'skill',skill:'constitution'},requires:['ruin_guard_25'],stage:'later',order:320},
{id:'warden_plate',name:'Forge a Warden Plate',description:'Forge a Warden Plate armor piece.',target:1,condition:{type:'forgedRecipe',recipe:'warden_plate'},reward:{coins:2000,fame:75},levelXpTarget:{type:'skill',skill:'constitution'},requires:['stone_beast_20'],stage:'later',order:330},
{id:'ancient_warden_10',name:'Defeat 10 Ancient Wardens',description:'Survive battles against Ancient Wardens.',target:10,condition:{type:'enemyKills',enemy:'ancient_warden'},reward:{coins:7500,fame:250},levelXpTarget:{type:'skill',skill:'combat'},requires:['stone_beast_20'],stage:'later',order:340},
{id:'ancient_brand',name:'Forge an Ancient Brand',description:'Forge an Ancient Brand weapon.',target:1,condition:{type:'forgedRecipe',recipe:'ancient_brand'},reward:{coins:5000,fame:250},levelXpTarget:{type:'skill',skill:'combat'},requires:['ancient_warden_10'],stage:'later',order:350},
{id:'gathering_tier3_any',name:'Forge any tier III gathering upgrade',description:'Perfect any gathering-upgrade family to tier III.',target:1,condition:{type:'anyUpgradeTier',families:GATHERING_UPGRADE_FAMILIES,tier:3},reward:{coins:10000,fame:500},levelXpTarget:{type:'lowestGathering'},requires:['gathering_tier2_any'],stage:'later',order:360},
{id:'gathering_tier3_all',name:'Forge all three tier III gathering upgrades',description:'Perfect all three gathering traditions.',target:3,condition:{type:'allUpgradeFamiliesTier',families:GATHERING_UPGRADE_FAMILIES,tier:3},reward:{coins:25000,fame:1000},levelXpTarget:{type:'lowestGathering'},requires:['gathering_tier2_all'],stage:'later',order:370},
{id:'tasks_25',name:'Claim 25 other tasks',description:'Claim twenty-five other task rewards.',target:25,condition:{type:'tasksClaimed'},reward:{fame:1000},levelXpTarget:{type:'lowestAny'},requires:['tasks_15'],stage:'later',order:380}
];
function taskById(id){return TASKS.find(t=>t.id===id)}
function taskState(task){Game.state.tasks=Game.state.tasks||{};return Game.state.tasks[task.id]||(Game.state.tasks[task.id]={})}
function taskIsClaimed(task){return !!(Game.state.tasks&&Game.state.tasks[task.id]&&Game.state.tasks[task.id].claimed)}
function taskIsUnlocked(task){if(taskIsClaimed(task))return true;const all=(task.requires||[]).every(id=>Game.state.tasks[id]&&Game.state.tasks[id].claimed);const any=!task.requiresAny||task.requiresAny.length===0||task.requiresAny.some(id=>Game.state.tasks[id]&&Game.state.tasks[id].claimed);return all&&any}
function highestUpgradeFamilyTier(family){let tier=0;(typeof FORGE_RECIPES!=='undefined'?FORGE_RECIPES:[]).forEach(r=>{if(r.upgradeFamily===family&&Game.state.upgrades&&Game.state.upgrades[r.result.id])tier=Math.max(tier,r.upgradeTier||0)});return tier}
function ownsToolTier(skill,tier){return Object.values(Game.state.equipment||{}).some(id=>itemDef(id).type==='tool'&&itemDef(id).skill===skill&&itemDef(id).tier>=tier)||(Game.state.ownedTools||[]).some(id=>itemDef(id).type==='tool'&&itemDef(id).skill===skill&&itemDef(id).tier>=tier)}
function ownedItemEverywhere(id){return ownedItemQuantity(id)>0||Object.values(Game.state.equipment||{}).includes(id)}
function taskProgress(task){const c=task.condition||{},s=Game.state;switch(c.type){case'counter':return s.counts[c.key]||0;case'skillLevel':return s.skills[c.skill].level;case'allSkillLevels':return Math.min(...c.skills.map(k=>s.skills[k].level));case'enemyKills':return s.kills[c.enemy]||0;case'upgradeOwned':return s.upgrades&&s.upgrades[c.upgrade]?1:0;case'anyUpgradeTier':return c.families.some(f=>highestUpgradeFamilyTier(f)>=c.tier)?1:0;case'allUpgradeFamiliesTier':return c.families.filter(f=>highestUpgradeFamilyTier(f)>=c.tier).length;case'anyToolTier':return (s.ownedTools||[]).some(id=>itemDef(id).type==='tool'&&itemDef(id).tier>=c.tier)||Object.values(s.equipment||{}).some(id=>itemDef(id).type==='tool'&&itemDef(id).tier>=c.tier)?1:0;case'allGatheringToolTier':return c.skills.filter(k=>ownsToolTier(k,c.tier)).length;case'regions':return Object.keys(s.discovered||{}).length;case'fameBought':return s.counts.fameBought||0;case'petCount':return Object.keys(s.pets&&s.pets.owned||{}).length;case'tasksClaimed':return s.counts.tasksClaimed||0;case'modeActions':return (((s.counts.gatheringModeActions||{})[c.skill]||{})[c.mode])||0;case'rareGoodsSold':return s.counts.rareGoodsSold||0;case'forgedAny':return s.counts.forgeCrafts||Object.values(s.counts.forgedByRecipe||{}).reduce((a,b)=>a+b,0);case'forgedRecipe':return (s.counts.forgedByRecipe||{})[c.recipe]||0;case'ownedItem':return ownedItemEverywhere(c.item)?1:0;default:return 0}}
function taskIsComplete(task){return taskProgress(task)>=task.target}
function taskIsClaimable(task){return taskIsUnlocked(task)&&!taskIsClaimed(task)&&taskIsComplete(task)}
function lowestNonMaxSkill(skills){const list=skills.filter(k=>Game.state.skills[k].level<CONFIG.MAX_LEVEL);const use=list.length?list:skills.slice();return use.sort((a,b)=>Game.state.skills[a].level-Game.state.skills[b].level||Game.state.skills[a].xp-Game.state.skills[b].xp||SKILLS.indexOf(a)-SKILLS.indexOf(b))[0]||null}
function resolveExplicitXpSkill(skill){if(!skill)return lowestNonMaxSkill(SKILLS);if(Game.state.skills[skill].level<CONFIG.MAX_LEVEL)return skill;if(GATHERING_SKILLS.includes(skill)){const g=lowestNonMaxSkill(GATHERING_SKILLS);if(g&&Game.state.skills[g].level<CONFIG.MAX_LEVEL)return g}if(skill==='combat'&&Game.state.skills.constitution.level<CONFIG.MAX_LEVEL)return'constitution';if(skill==='constitution'&&Game.state.skills.combat.level<CONFIG.MAX_LEVEL)return'combat';const any=lowestNonMaxSkill(SKILLS);return any&&Game.state.skills[any].level<CONFIG.MAX_LEVEL?any:null}
function resolveTaskXpSkill(task){const x=task.levelXpTarget;if(x.type==='skill')return resolveExplicitXpSkill(x.skill);if(x.type==='lowestGathering')return resolveExplicitXpSkill(lowestNonMaxSkill(GATHERING_SKILLS));return resolveExplicitXpSkill(lowestNonMaxSkill(SKILLS))}
function fullLevelXp(skill){const level=Game.state.skills[skill].level;if(level>=CONFIG.MAX_LEVEL)return 0;return xpForLevel(level+1)-xpForLevel(level)}
function snapshotTaskXpReward(task){const st=taskState(task);if(st.xpReward)return st.xpReward;const skill=resolveTaskXpSkill(task);st.completed=true;st.xpGranted=!!st.xpGranted;if(!skill)st.xpReward={skill:null,amount:0,fameFallback:1000};else st.xpReward={skill,amount:fullLevelXp(skill),fameFallback:0};return st.xpReward}
function grantTaskXpReward(task){const st=taskState(task);const r=st.xpReward||snapshotTaskXpReward(task);if(st.xpGranted)return false;if(r.fameFallback)Game.state.fame+=r.fameFallback;else if(r.skill&&r.amount)gainXp(r.skill,r.amount);st.xpGranted=true;return true}
function snapshotCompletedTaskRewards(){normalizeTaskProgress(false);TASKS.forEach(t=>{if(!taskIsClaimed(t)&&taskIsComplete(t))snapshotTaskXpReward(t)})}
function taskRewardText(task){const r=task.reward||{},parts=[];if(r.coins)parts.push(`${r.coins.toLocaleString()} coins`);if(r.fame)parts.push(`${r.fame.toLocaleString()} Fame`);if(r.inv)parts.push(`+${r.inv} inventory slots`);if(r.xp)Object.keys(r.xp).forEach(k=>parts.push(`${r.xp[k].toLocaleString()} ${formatSkill(k)} XP`));return parts.length?parts.join(', '):'None'}
function taskRequirementText(task){const c=task.condition;return `${Math.min(taskProgress(task),task.target).toLocaleString()} / ${task.target.toLocaleString()}`}
function taskXpRewardText(task,prefix='XP reward'){const st=Game.state.tasks&&Game.state.tasks[task.id];const r=st&&st.xpReward;if(r){if(r.fameFallback)return `${prefix}: ${r.fameFallback.toLocaleString()} Fame because every skill is level 99`;return `${prefix}: ${r.amount.toLocaleString()} ${formatSkill(r.skill)} XP`}const x=task.levelXpTarget;if(x.type==='skill')return `${prefix}: One full level in ${formatSkill(x.skill)}`;if(x.type==='lowestGathering')return `${prefix}: One full level in your lowest gathering skill`;return `${prefix}: One full level in your lowest non-max skill`}
function prerequisiteText(task){const names=[];(task.requires||[]).forEach(id=>names.push(taskById(id)?.name||id));if(task.requiresAny&&task.requiresAny.length)names.push(`one of: ${task.requiresAny.map(id=>taskById(id)?.name||id).join(', ')}`);return names.join('; ')}
function inferForgeProgress(){const counts=Game.state.counts;counts.forgedByRecipe=counts.forgedByRecipe||{};(typeof FORGE_RECIPES!=='undefined'?FORGE_RECIPES:[]).forEach(r=>{if(!r.repeatable&&r.result&&r.result.type==='upgrade'&&Game.state.upgrades&&Game.state.upgrades[r.result.id])counts.forgedByRecipe[r.id]=Math.max(counts.forgedByRecipe[r.id]||0,1)});['warden_plate','ancient_brand'].forEach(id=>{if(ownedItemEverywhere(id))counts.forgedByRecipe[id]=Math.max(counts.forgedByRecipe[id]||0,1)});const min=Object.values(counts.forgedByRecipe).reduce((a,b)=>a+(Number(b)||0),0);counts.forgeCrafts=Math.max(counts.forgeCrafts||0,min)}
function normalizeTaskProgress(runRetro=true){Game.state.counts=Game.state.counts||{};const c=Game.state.counts;c.rareGoodsSold=c.rareGoodsSold||0;c.forgeCrafts=c.forgeCrafts||0;c.forgedByRecipe=c.forgedByRecipe||{};c.gatheringModeActions=c.gatheringModeActions||{};c.gatheringModeActions.woodcutting=c.gatheringModeActions.woodcutting||{};c.gatheringModeActions.woodcutting.grovekeeping=c.gatheringModeActions.woodcutting.grovekeeping||0;c.gatheringModeActions.mining=c.gatheringModeActions.mining||{};c.gatheringModeActions.mining.prospecting=c.gatheringModeActions.mining.prospecting||0;c.gatheringModeActions.fishing=c.gatheringModeActions.fishing||{};c.gatheringModeActions.fishing.salvage=c.gatheringModeActions.fishing.salvage||0;Game.state.tasks=Game.state.tasks||{};Game.state.migrations=Game.state.migrations||{};inferForgeProgress();const claimedRecords=Object.values(Game.state.tasks).filter(st=>st&&st.claimed).length;c.tasksClaimed=Math.max(c.tasksClaimed||0,claimedRecords);if(runRetro){TASKS.slice().sort((a,b)=>a.order-b.order).forEach(t=>{const st=Game.state.tasks[t.id];if(st&&st.claimed&&!st.xpGranted){snapshotTaskXpReward(t);grantTaskXpReward(t);st.completed=true;st.claimed=true;logMsg(`Retroactive task XP awarded: ${t.name}`,'rare')}});Game.state.migrations.taskLevelXpV1=true}}
const claimingTasks={};
function claimTask(id){const task=taskById(id);if(!task||claimingTasks[id])return;normalizeTaskProgress(false);const st=taskState(task);if(st.claimed||!taskIsUnlocked(task)||!taskIsComplete(task))return;claimingTasks[id]=true;snapshotTaskXpReward(task);const r=task.reward||{};if(r.coins)addItem('coins',r.coins);if(r.fame)Game.state.fame+=r.fame;if(r.inv)Game.state.invCap+=r.inv;if(r.xp)Object.keys(r.xp).forEach(k=>gainXp(k,r.xp[k]));grantTaskXpReward(task);st.claimed=true;st.completed=true;Game.state.counts.tasksClaimed=(Game.state.counts.tasksClaimed||0)+1;logMsg(`Task complete: ${task.name}`,'rare');const xr=st.xpReward;if(xr.fameFallback)logMsg(`Task XP reward: ${xr.fameFallback.toLocaleString()} Fame fallback.`,'rare');else logMsg(`Task XP reward: ${xr.amount.toLocaleString()} ${formatSkill(xr.skill)} XP.`,'rare');delete claimingTasks[id];snapshotCompletedTaskRewards();openTasks()}
function recordGatheringModeAction(skill){const mode=(Game.state.gatheringModes&&Game.state.gatheringModes[skill])||(skill==='fishing'&&Game.state.fishing&&Game.state.fishing.mode);const map={woodcutting:'grovekeeping',mining:'prospecting',fishing:'salvage'};if(mode!==map[skill])return;normalizeTaskProgress(false);Game.state.counts.gatheringModeActions[skill][mode]=(Game.state.counts.gatheringModeActions[skill][mode]||0)+1}
