const assert=require('assert'),fs=require('fs'),vm=require('vm');
class El{constructor(){this.style={};this.classList={add(){},remove(){},toggle(){}};this.innerHTML='';this.textContent='';}}
const elements={};const context={console,Date,Math,performance:{now:()=>1000},document:{getElementById:id=>elements[id]||(elements[id]=new El())},confirm:()=>true,localStorage:{getItem(){return null},setItem(){}}};context.window=context;vm.createContext(context);
['js/config.js','js/data.js','js/state.js','js/pity.js','js/collection-log.js','js/inventory.js','js/forge.js','js/ui.js','js/shop.js','js/save.js','js/combat.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),context,{filename:f}));
context.sound=()=>{};context.cancel=()=>{};const Game=vm.runInContext('Game',context),ENEMIES=vm.runInContext('ENEMIES',context),FORGE_RECIPES=vm.runInContext('FORGE_RECIPES',context),ITEM=vm.runInContext('ITEM',context);
const drops=id=>ENEMIES.find(e=>e.id===id).drops;const drop=(e,id)=>drops(e).find(d=>d.id===id);const no=(e,id)=>assert(!drop(e,id),`${e} must not drop ${id}`);const rate=(e,id,r)=>assert.strictEqual(drop(e,id).rate,r,`${e} ${id}`);
['cave_rat','moss_creature','ruin_guard','stone_beast','ancient_warden'].forEach(e=>no(e,'ancient_brand'));
rate('cave_rat','rat_tail',1/3);rate('cave_rat','rat_charm',1/128);rate('moss_creature','moss_fiber',1/3);rate('moss_creature','moss_crown',1/128);rate('ruin_guard','ruin_shard',1/2);rate('ruin_guard','guard_mail',1/75);rate('ruin_guard','sentinel_eye',1/256);rate('ruin_guard','rubble_imp',1/400);rate('stone_beast','stone_hide',1/2);rate('stone_beast','stone_heart',1/40);rate('stone_beast','rubble_imp',1/400);rate('ancient_warden','warden_sigil',1);rate('ancient_warden','ancient_relic',1/100);rate('ancient_warden','warden_echo',1/200);
ENEMIES.filter(e=>e.id!=='ancient_warden').forEach(e=>no(e.id,'warden_echo'));['cave_rat','moss_creature'].forEach(e=>no(e,'rubble_imp'));
assert.deepStrictEqual(JSON.parse(JSON.stringify(context.forgeRecipe('pack_rat_satchel').materials)),{rat_tail:20,rat_charm:1});assert.strictEqual(context.forgeRecipe('pack_rat_satchel').coins,500);assert.deepStrictEqual(JSON.parse(JSON.stringify(context.forgeRecipe('mossbound_charm').materials)),{moss_fiber:20,moss_crown:1});assert.strictEqual(context.forgeRecipe('mossbound_charm').coins,1000);assert.deepStrictEqual(JSON.parse(JSON.stringify(context.forgeRecipe('sentinel_lens').materials)),{ruin_shard:20,sentinel_eye:1});assert.strictEqual(context.forgeRecipe('sentinel_lens').coins,1500);assert.deepStrictEqual(JSON.parse(JSON.stringify(context.forgeRecipe('warden_plate').materials)),{stone_hide:30,stone_heart:3});assert.strictEqual(context.forgeRecipe('warden_plate').coins,2500);assert.deepStrictEqual(JSON.parse(JSON.stringify(context.forgeRecipe('ancient_brand').materials)),{warden_sigil:10,ancient_relic:1});assert.strictEqual(context.forgeRecipe('ancient_brand').coins,5000);
function setInv(items,coins=999999){Game.state=context.newState();Game.state.coins=coins;Game.state.inventory=Object.entries(items).map(([id,qty])=>({id,qty}));Game.state.bank={};Game.state.upgrades={pack_rat_satchel:false,mossbound_charm:false,sentinel_lens:false};}
setInv({rat_tail:19,rat_charm:1},500);context.craftRecipe('pack_rat_satchel');assert.strictEqual(context.ownedQuantity('rat_tail'),19);assert.strictEqual(Game.state.coins,500);
setInv({rat_tail:20,rat_charm:1},500);context.craftRecipe('pack_rat_satchel');assert.strictEqual(Game.state.coins,0);assert.strictEqual(Game.state.invCap,28);context.craftRecipe('pack_rat_satchel');assert.strictEqual(Game.state.invCap,28);
setInv({moss_fiber:20,moss_crown:1},1000);assert.strictEqual(context.getRegenInterval(),3000);context.craftRecipe('mossbound_charm');assert.strictEqual(context.getRegenInterval(),1500);
setInv({ruin_shard:20,sentinel_eye:1},1500);assert.strictEqual(context.sentinelAccuracyBonus(),0);context.craftRecipe('sentinel_lens');assert.strictEqual(context.sentinelAccuracyBonus(),8);context.craftRecipe('sentinel_lens');assert.strictEqual(context.sentinelAccuracyBonus(),8);
setInv({stone_hide:30,stone_heart:3},2500);context.craftRecipe('warden_plate');assert.strictEqual(context.countInventoryItem('warden_plate'),1);
setInv({warden_sigil:10,ancient_relic:1},5000);context.craftRecipe('ancient_brand');assert.strictEqual(context.countInventoryItem('ancient_brand'),1);
setInv({stone_hide:30,stone_heart:3},2500);Game.state.inventory=Array.from({length:Game.state.invCap},(_,i)=>({id:i<2?['stone_hide','stone_heart'][i]:'brushwood',qty:i===0?30:i===1?3:1}));context.craftRecipe('warden_plate');assert.strictEqual(context.countInventoryItem('warden_plate'),0);
Game.state=context.newState();Game.state.upgrades={};Game.state.inventory=[{id:'ancient_brand',qty:1}];context.normalizeLoadedState();assert.strictEqual(Game.state.upgrades.pack_rat_satchel,false);assert.strictEqual(context.countInventoryItem('ancient_brand'),1);Game.state.upgrades.pack_rat_satchel=true;Game.state.upgrades.mossbound_charm=true;Game.state.upgrades.sentinel_lens=true;context.die();assert(Game.state.upgrades.pack_rat_satchel&&Game.state.upgrades.mossbound_charm&&Game.state.upgrades.sentinel_lens);
context.openBestiary();assert(elements.modalBody.innerHTML.includes('50% (1 in 2)'));Game.state.collection.rat_charm=0;context.openBestiary();assert(elements.modalBody.innerHTML.includes('???'));
const cats=context.categories();assert(cats.Materials.includes('rat_tail'));Game.state.inventory=[{id:'rat_tail',qty:5},{id:'brushwood',qty:1}];Game.state.coins=0;context.sellAll();assert.strictEqual(context.countInventoryItem('rat_tail'),5);
console.log('Combat forge bestiary tests passed');
