const assert=require('assert'),fs=require('fs'),vm=require('vm');
class El{constructor(){this.style={};this.classList={add(){},remove(){},toggle(){}};this.innerHTML='';}}
const elements={},logs=[];const context={console,Date,performance:{now:()=>1000},document:{getElementById:id=>elements[id]||(elements[id]=new El())},localStorage:{getItem(){return null},setItem(){}},confirm:()=>true};context.window=context;context.Math=Object.create(Math);vm.createContext(context);
['js/config.js','js/data.js','js/state.js','js/collection-log.js','js/inventory.js','js/pity.js','js/forge.js','js/actions.js','js/ui.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),context,{filename:f}));
context.sound=()=>{};context.logMsg=(m,c='')=>logs.unshift({m,c});
const Game=vm.runInContext('Game',context),ENEMIES=vm.runInContext('ENEMIES',context),ITEM=vm.runInContext('ITEM',context);
const allDrops=()=>ENEMIES.flatMap(e=>e.drops.map(d=>[e,d]));const by=(eid,did)=>{const e=ENEMIES.find(x=>x.id===eid);return [e,e.drops.find(d=>d.id===did)]};
const eligible=allDrops().filter(([e,d])=>d.pity).map(([e,d])=>`${e.id}:${d.id}`).sort();
assert.strictEqual(JSON.stringify(eligible),JSON.stringify(['ancient_warden:ancient_relic','cave_rat:rat_charm','moss_creature:moss_crown','ruin_guard:guard_mail','ruin_guard:sentinel_eye','stone_beast:stone_heart'].sort()));
['coins','bones','rat_tail','moss_fiber','ruin_shard','stone_hide','warden_sigil','rubble_imp','warden_echo'].forEach(id=>assert(!allDrops().some(([,d])=>d.id===id&&d.pity),`${id} excluded`));
const rate=context.enemyDropPityRate,base=1/128,close=(a,b,t=1e-10)=>assert(Math.abs(a-b)<=t,`${a} != ${b}`);
close(rate(base,1),base);close(rate(base,128),base);assert(rate(base,129)>base);close(rate(base,192),0.011688232421875);close(rate(base,227),0.0300033873,1e-10);close(rate(base,228),0.0309136654,1e-10);close(rate(base,256),0.06982421875);close(rate(base,320),0.321746826171875);assert(rate(base,383)<1);close(rate(base,384),1);close(rate(base,500),1);for(let i=-5;i<500;i++)assert(rate(base,i)>=base&&rate(base,i)<=1);
assert.strictEqual(context.enemyDropPityGuaranteeAttempt(by('ruin_guard','guard_mail')[1]),225);assert.strictEqual(context.enemyDropPityGuaranteeAttempt(by('ruin_guard','sentinel_eye')[1]),768);assert.strictEqual(context.enemyDropPityGuaranteeAttempt(by('stone_beast','stone_heart')[1]),120);assert.strictEqual(context.enemyDropPityGuaranteeAttempt(by('ancient_warden','ancient_relic')[1]),300);for(let i=1;i<=75;i++)assert.strictEqual(rate(1/75,i),1/75);
function reset(){Game.state=context.newState();logs.length=0;context.normalizeEnemyDropPity();}
reset();Game.state.pity.enemyDrops['ruin_guard:guard_mail']=224;Game.state.pity.enemyDrops['ruin_guard:sentinel_eye']=7;context.settleEnemyDropRoll({eligible:true,key:'ruin_guard:guard_mail'},true);assert.strictEqual(Game.state.pity.enemyDrops['ruin_guard:guard_mail'],0);assert.strictEqual(Game.state.pity.enemyDrops['ruin_guard:sentinel_eye'],7);
reset();let [e,drop]=by('cave_rat','rat_charm');context.Math.random=()=>0.99;let r=context.rollEnemyDrop(e.id,drop);assert(!r.dropped);assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],1);assert.strictEqual(context.countInventoryItem('rat_charm'),0);
context.Math.random=()=>0;Game.state.pity.enemyDrops['cave_rat:rat_charm']=127;r=context.rollEnemyDrop(e.id,drop);assert(r.dropped);let delivered=context.addItem(drop.id,1);context.settleEnemyDropRoll(r,delivered);assert.strictEqual(context.countInventoryItem('rat_charm'),1);assert.strictEqual(Game.state.collection.rat_charm,1);assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],0);
reset();Game.state.inventory=Array.from({length:Game.state.invCap},(_,i)=>({id:'brushwood',qty:i+1}));Game.state.pity.enemyDrops['cave_rat:rat_charm']=383;context.Math.random=()=>0.999;r=context.rollEnemyDrop(e.id,drop);assert(r.dropped);delivered=context.addItem(drop.id,1);if(!delivered)context.logMsg(`${ITEM[drop.id].name} was lost because your inventory was full.`,'bad');context.settleEnemyDropRoll(r,delivered);assert.strictEqual(context.countInventoryItem('rat_charm'),0);assert.strictEqual(Game.state.collection.rat_charm||0,0);assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],384);assert(logs[0].m.includes('was lost because your inventory was full'));
r=context.rollEnemyDrop(e.id,drop);assert(r.dropped);assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],384);Game.state.inventory.pop();delivered=context.addItem(drop.id,1);context.settleEnemyDropRoll(r,delivered);assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],0);
reset();const coins=by('cave_rat','coins')[1];context.Math.random=()=>0.99;r=context.rollEnemyDrop('cave_rat',coins);assert(r.dropped);assert(!Game.state.pity.enemyDrops['cave_rat:coins']);assert.strictEqual(coins.min,8);assert.strictEqual(coins.max,30);assert.strictEqual(coins.rate,1);
for(const [me,md] of allDrops().filter(([,d])=>d.pity)){reset();Game.state.kills[me.id]=9999;context.normalizeEnemyDropPity({migrateLegacy:true});assert.strictEqual(Game.state.pity.enemyDrops[`${me.id}:${md.id}`],context.enemyDropPityGuaranteeAttempt(md)-1);reset();Game.state.kills[me.id]=7;Game.state.collection[md.id]=1;context.normalizeEnemyDropPity({migrateLegacy:true});assert.strictEqual(Game.state.pity.enemyDrops[`${me.id}:${md.id}`],0);}
reset();Game.state.kills.cave_rat=227;context.normalizeEnemyDropPity({migrateLegacy:true});assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],227);assert.strictEqual(context.enemyDropPityNextAttempt('cave_rat',drop),228);close(context.enemyDropCurrentRate('cave_rat',drop),0.0309136654,1e-10);assert.strictEqual(context.enemyDropKillsUntilGuarantee('cave_rat',drop),157);
reset();Game.state.kills.cave_rat=1000;context.normalizeEnemyDropPity({migrateLegacy:true});assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],383);assert.strictEqual(context.enemyDropCurrentRate('cave_rat',drop),1);
Game.state.pity.enemyDrops['cave_rat:rat_charm']=12;context.normalizeEnemyDropPity();assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],12);
Game.state.pity={enemyDrops:{'cave_rat:rat_charm':'12.9','moss_creature:moss_crown':-1,'ruin_guard:guard_mail':Infinity,'ruin_guard:sentinel_eye':'bad','stone_beast:stone_heart':999,'old:key':5}};context.normalizeEnemyDropPity();assert.strictEqual(Game.state.pity.enemyDrops['cave_rat:rat_charm'],12);assert.strictEqual(Game.state.pity.enemyDrops['moss_creature:moss_crown'],0);assert.strictEqual(Game.state.pity.enemyDrops['ruin_guard:guard_mail'],0);assert.strictEqual(Game.state.pity.enemyDrops['ruin_guard:sentinel_eye'],0);assert.strictEqual(Game.state.pity.enemyDrops['stone_beast:stone_heart'],120);assert(!('old:key' in Game.state.pity.enemyDrops));
reset();Game.state.pity.enemyDrops['cave_rat:rat_charm']=227;context.openBestiary();let html=elements.modalBody.innerHTML;assert(html.includes('Base chance: 0.78% (1 in 128)'));assert(html.includes('Current chance: 3.09%'));assert(html.includes('Dry streak: 227'));assert(html.includes('Guaranteed by attempt: 384'));assert(html.includes('Kills until guaranteed: 157'));assert(html.includes('Chance: 33% (1 in 3)'));assert(html.includes('<b>???</b>'));assert(!html.includes('Rat Charm'));
console.log('Enemy drop pity tests passed');
