const assert=require('assert'),fs=require('fs'),vm=require('vm');
const context={console,performance:{now:()=>0},localStorage:{getItem:()=>null,setItem:()=>{}},document:{},confirm:()=>true};context.global=context;context.window=context;vm.createContext(context);
['js/config.js','js/data.js','js/state.js','js/pity.js','js/collection-log.js','js/inventory.js','js/forge.js','js/shop.js','js/gathering-modes.js','js/actions.js','js/save.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),context,{filename:f}));
const G=vm.runInContext('Game',context),RES=vm.runInContext('RESOURCES',context),REC=vm.runInContext('FORGE_RECIPES',context);
context.modal=()=>{};context.openShop=()=>{};context.openForge=()=>{};context.sound=()=>{};context.setAction=a=>{G.state.action=a};
function reset(){G.state=context.newState();G.objects=[];context.normalizeGatheringModes()}
function add(id,qty,bank=false){if(bank)G.state.bank[id]=(G.state.bank[id]||0)+qty;else for(let i=0;i<qty;i++)context.addItem(id,1)}
function snap(){return JSON.stringify({coins:G.state.coins,inv:G.state.inventory,bank:G.state.bank,up:G.state.upgrades})}
reset();[['woodcutting','amber_seed','golden_bough'],['mining','crystal_gem','meteor_core'],['fishing','sunken_relic','pearl_hook']].forEach(([sk,c,k])=>{const r=RES[sk][0],t=context.gatheringRareTable(r);assert.strictEqual(t[0].id,c);assert.strictEqual(t[0].rate,.02);assert.strictEqual(t[1].id,k);assert.strictEqual(t[1].rate,.002);});
['heartwood_totem','deepcore_resonator','relicbound_tackle'].forEach(f=>{let r=context.forgeRecipe(`${f}_1`);assert.deepStrictEqual(Object.values(r.materials),[20,1]);assert.strictEqual(r.coins,2500);assert.strictEqual(r.repeatable,false);assert.strictEqual(r.upgradeFamily,f);assert.strictEqual(r.upgradeTier,1);r=context.forgeRecipe(`${f}_2`);assert.deepStrictEqual(Object.values(r.materials),[50,2]);assert.strictEqual(r.coins,7500);assert.strictEqual(r.requiresUpgrade,`${f}_1`);r=context.forgeRecipe(`${f}_3`);assert.deepStrictEqual(Object.values(r.materials),[100,3]);assert.strictEqual(r.coins,20000);assert.strictEqual(r.requiresUpgrade,`${f}_2`);});
reset();assert.strictEqual(context.setGatheringMode('woodcutting','grovekeeping'),false);assert.strictEqual(G.state.gatheringModes.woodcutting,'normal');G.state.upgrades.heartwood_totem_1=true;assert.strictEqual(context.setGatheringMode('woodcutting','grovekeeping'),true);assert.strictEqual(context.gatheringIntervalMultiplier(RES.woodcutting[0]),1.25);assert.strictEqual(context.gatheringRareTable(RES.woodcutting[0])[0].rate,.03);assert.strictEqual(context.gatheringDepletionChance(RES.woodcutting[0]),RES.woodcutting[0].deplete*.8);G.state.upgrades.heartwood_totem_2=true;assert.strictEqual(context.gatheringIntervalMultiplier(RES.woodcutting[0]),1.15);assert.strictEqual(context.gatheringDepletionChance(RES.woodcutting[0]),RES.woodcutting[0].deplete*.65);G.state.upgrades.heartwood_totem_3=true;assert.strictEqual(context.gatheringIntervalMultiplier(RES.woodcutting[0]),1.05);assert.strictEqual(context.gatheringDepletionChance(RES.woodcutting[0]),RES.woodcutting[0].deplete*.5);
reset();G.state.upgrades.deepcore_resonator_1=true;context.setGatheringMode('mining','prospecting');let vals=[0.04,0.06],i=0;context.Math=Object.create(Math);context.Math.random=()=>vals[i++];assert.strictEqual(context.gatheringBonusQuantity(RES.mining[0]),1);G.state.upgrades.deepcore_resonator_2=true;assert.strictEqual(context.gatheringModeSettings('mining').bonusQuantityChance,.1);G.state.upgrades.deepcore_resonator_3=true;assert.strictEqual(context.gatheringModeSettings('mining').bonusQuantityChance,.15);
reset();G.state.upgrades={relicbound_tackle_2:true};G.state.fishing={mode:'salvage'};context.normalizeGatheringModes();assert.strictEqual(G.state.upgrades.relicbound_tackle_1,true);assert.strictEqual(G.state.gatheringModes.fishing,'salvage');G.state.upgrades={heartwood_totem_3:true,deepcore_resonator_2:true};G.state.gatheringModes={woodcutting:'grovekeeping',mining:'prospecting',fishing:'bad'};context.normalizeGatheringModes();assert.strictEqual(G.state.upgrades.heartwood_totem_1,true);assert.strictEqual(G.state.upgrades.deepcore_resonator_1,true);assert.strictEqual(G.state.gatheringModes.fishing,'normal');
reset();['amber_seed','golden_bough','crystal_gem','meteor_core','sunken_relic','pearl_hook'].forEach((id,idx)=>assert.strictEqual(context.rareGoodSummary(id).value,[50,500,50,500,50,500][idx]));assert.strictEqual(context.rareGoodReservation('amber_seed').qty,20);assert.strictEqual(context.rareGoodReservation('golden_bough').qty,1);G.state.upgrades.heartwood_totem_1=true;assert.strictEqual(context.rareGoodReservation('amber_seed').qty,50);G.state.upgrades.heartwood_totem_2=true;assert.strictEqual(context.rareGoodReservation('amber_seed').qty,100);G.state.upgrades.heartwood_totem_3=true;assert.strictEqual(context.rareGoodReservation('amber_seed').qty,0);assert.strictEqual(context.rareGoodReservation('crystal_gem').qty,20);
reset();G.state.invCap=50;add('crystal_gem',25);add('crystal_gem',10,true);G.state.coins=0;context.sellRareGoodExcess('crystal_gem');assert.strictEqual(context.ownedItemQuantity('crystal_gem'),20);assert.strictEqual(G.state.coins,750);let confirmed=0;context.confirm=()=>{confirmed++;return false};context.sellRareGood('crystal_gem',1);assert.strictEqual(confirmed,1);assert.strictEqual(context.ownedItemQuantity('crystal_gem'),20);context.confirm=()=>true;context.sellRareGood('crystal_gem',1);assert.strictEqual(context.ownedItemQuantity('crystal_gem'),19);assert.strictEqual(G.state.coins,800);['0','-1','1.5','abc'].forEach(q=>{const b=snap();context.sellRareGood('crystal_gem',q);assert.strictEqual(snap(),b)});
reset();const beforeKey=context.CONFIG.SAVE_KEY,beforeVer=context.CONFIG.SAVE_VERSION;G.state.invCap=0;G.state.collection={};let logs=[];context.logMsg=t=>logs.push(t);context.rollRare([{id:'amber_seed',rate:1}]);assert.strictEqual(G.state.collection.amber_seed,undefined);assert(logs.some(x=>x.includes('lost')));assert.strictEqual(context.CONFIG.SAVE_KEY,beforeKey);assert.strictEqual(context.CONFIG.SAVE_VERSION,beforeVer);
console.log('Gathering upgrade systems tests passed');
