const assert=require('assert'),fs=require('fs'),vm=require('vm');
const context={console,performance:{now:()=>1000},Math:Object.create(Math),window:{},document:{getElementById:()=>({innerHTML:'',classList:{remove(){},add(){}},textContent:'',style:{}})},localStorage:{getItem:()=>null,setItem(){},removeItem(){}},confirm:()=>true,location:{reload(){}},modal(){},sound(){},discover(){}};
context.window=context;context.Math.random=Math.random;vm.createContext(context);
['js/config.js','js/data.js','js/state.js','js/collection-log.js','js/inventory.js','js/forge.js','js/shop.js','js/gathering-modes.js','js/actions.js','js/save.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),context,{filename:f}));
const G=vm.runInContext('Game',context),RESOURCES=vm.runInContext('RESOURCES',context);
function reset(){G.state=context.newState();G.objects=[];G.shopMessage=null;G.forgeMessage=null;context.normalizeFishingState();}
function add(id,n,bank=false){if(bank)G.state.bank[id]=(G.state.bank[id]||0)+n;else for(let i=0;i<n;i++)G.state.inventory.push({id,qty:1});}
function snap(){return JSON.stringify({coins:G.state.coins,inv:G.state.inventory,bank:G.state.bank,up:G.state.upgrades});}
reset();let fish=RESOURCES.fishing[0];assert.strictEqual(fish.rare[0].id,'sunken_relic');assert.strictEqual(fish.rare[0].rate,.02);assert.strictEqual(fish.rare[1].id,'pearl_hook');assert.strictEqual(fish.rare[1].rate,.002);assert.strictEqual(context.fishingRareTable(fish)[0].rate,.02);assert.strictEqual(context.fishingRareTable(fish)[1].rate,.002);
assert.deepStrictEqual(JSON.parse(JSON.stringify(context.forgeRecipe('relicbound_tackle_1').materials)),{sunken_relic:20,pearl_hook:1});assert.strictEqual(context.forgeRecipe('relicbound_tackle_1').coins,2500);
assert.deepStrictEqual(JSON.parse(JSON.stringify(context.forgeRecipe('relicbound_tackle_2').materials)),{sunken_relic:50,pearl_hook:2});assert.strictEqual(context.forgeRecipe('relicbound_tackle_2').coins,7500);
assert.deepStrictEqual(JSON.parse(JSON.stringify(context.forgeRecipe('relicbound_tackle_3').materials)),{sunken_relic:100,pearl_hook:3});assert.strictEqual(context.forgeRecipe('relicbound_tackle_3').coins,20000);
reset();add('sunken_relic',50);add('pearl_hook',2);G.state.coins=7500;assert.strictEqual(context.canCraftRecipe(context.forgeRecipe('relicbound_tackle_2')).reason,'Requires Relicbound Tackle I');
G.state.upgrades.relicbound_tackle_1=true;assert.strictEqual(context.canCraftRecipe(context.forgeRecipe('relicbound_tackle_3')).reason,'Requires Relicbound Tackle II');
reset();add('sunken_relic',19);add('pearl_hook',1);G.state.coins=2500;let before=snap();context.craftRecipe('relicbound_tackle_1');assert.strictEqual(snap(),before);
reset();add('sunken_relic',20);add('pearl_hook',1);G.state.coins=2500;context.craftRecipe('relicbound_tackle_1');assert.strictEqual(G.state.upgrades.relicbound_tackle_1,true);assert.strictEqual(G.state.coins,0);before=snap();context.craftRecipe('relicbound_tackle_1');assert.strictEqual(snap(),before);
assert.strictEqual(context.setFishingMode('salvage'),true);assert.strictEqual(G.state.fishing.mode,'salvage');assert.strictEqual(context.fishingIntervalMultiplier(fish),1.25);assert.strictEqual(context.fishingRareTable(fish)[0].rate,.03);assert.strictEqual(context.fishingRareTable(fish)[1].rate,.003);
G.state.upgrades.relicbound_tackle_2=true;assert.strictEqual(context.fishingIntervalMultiplier(fish),1.15);assert.strictEqual(context.fishingRareTable(fish)[0].rate,.04);assert.strictEqual(context.fishingRareTable(fish)[1].rate,.004);
G.state.upgrades.relicbound_tackle_3=true;assert.strictEqual(context.fishingIntervalMultiplier(fish),1.05);assert.strictEqual(context.fishingRareTable(fish)[0].rate,.05);assert.strictEqual(context.fishingRareTable(fish)[1].rate,.005);assert.strictEqual(context.fishingRareTable(fish).length,2);
reset();assert.strictEqual(context.setFishingMode('salvage'),false);assert.strictEqual(G.state.fishing.mode,'normal');assert.strictEqual(context.skillPetChance(123),context.skillPetChance(123));assert.strictEqual(fish.deplete,.006);assert.strictEqual(fish.respawn,10000);assert.strictEqual(RESOURCES.woodcutting[0].rare[0].rate,.02);assert.strictEqual(RESOURCES.mining[0].rare[1].rate,.002);
assert.strictEqual(context.itemDef('sunken_relic').value,50);assert.strictEqual(context.itemDef('pearl_hook').value,500);
reset();add('sunken_relic',21);add('pearl_hook',2);G.state.inventory.push({id:'bones',qty:5});context.sellAll();assert.strictEqual(context.ownedItemQuantity('sunken_relic'),21);assert.strictEqual(context.ownedItemQuantity('pearl_hook'),2);assert.strictEqual(G.state.coins,90);
assert.strictEqual(context.rareGoodReservation('sunken_relic').qty,20);assert.strictEqual(context.rareGoodReservation('pearl_hook').qty,1);G.state.upgrades.relicbound_tackle_1=true;assert.strictEqual(context.rareGoodReservation('sunken_relic').qty,50);assert.strictEqual(context.rareGoodReservation('pearl_hook').qty,2);G.state.upgrades.relicbound_tackle_2=true;assert.strictEqual(context.rareGoodReservation('sunken_relic').qty,100);assert.strictEqual(context.rareGoodReservation('pearl_hook').qty,3);G.state.upgrades.relicbound_tackle_3=true;assert.strictEqual(context.rareGoodReservation('sunken_relic').qty,0);
reset();add('sunken_relic',25);add('sunken_relic',10,true);G.state.coins=0;context.sellRareGoodExcess('sunken_relic');assert.strictEqual(context.ownedItemQuantity('sunken_relic'),20);assert.strictEqual(G.state.coins,750);assert.strictEqual(context.inventoryItemQuantity('sunken_relic'),10);assert.strictEqual(context.bankItemQuantity('sunken_relic'),10);
reset();add('pearl_hook',2);G.state.coins=0;let confirmed=0;context.confirm=()=>{confirmed++;return false};context.sellRareGood('pearl_hook',1);assert.strictEqual(confirmed,0);assert.strictEqual(G.state.coins,500);context.confirm=()=>{confirmed++;return false};context.sellRareGood('pearl_hook',1);assert.strictEqual(context.ownedItemQuantity('pearl_hook'),1);assert.strictEqual(G.state.coins,500);context.confirm=()=>{confirmed++;return true};context.sellRareGood('pearl_hook',1);assert.strictEqual(context.ownedItemQuantity('pearl_hook'),0);assert.strictEqual(G.state.coins,1000);['0','-1','1.5','abc'].forEach(q=>{const b=snap();context.sellRareGood('sunken_relic',q);assert.strictEqual(snap(),b)});
reset();add('sunken_relic',1);add('sunken_relic',3,true);context.removeOwnedItemQuantity('sunken_relic',3);assert.strictEqual(context.inventoryItemQuantity('sunken_relic'),0);assert.strictEqual(context.bankItemQuantity('sunken_relic'),1);
reset();G.state.upgrades={relicbound_tackle_2:true};G.state.fishing={mode:'salvage'};context.normalizeFishingState();assert.strictEqual(G.state.upgrades.relicbound_tackle_1,true);G.state.upgrades={relicbound_tackle_3:true};context.normalizeFishingState();assert.strictEqual(G.state.upgrades.relicbound_tackle_1,true);assert.strictEqual(G.state.upgrades.relicbound_tackle_2,true);G.state.upgrades={};G.state.fishing={mode:'salvage'};context.normalizeFishingState();assert.strictEqual(G.state.fishing.mode,'normal');
reset();G.state.invCap=0;G.state.inventory=[];G.state.collection={};let logs=[];context.logMsg=(t)=>logs.push(t);context.rollRare([{id:'sunken_relic',rate:1}]);assert.strictEqual(G.state.collection.sunken_relic,undefined);assert(logs.some(x=>x.includes('lost')));
console.log('Relicbound tackle and rare goods tests passed');
